apiVersion: batch/v1beta1
kind: CronJob
metadata: 
    name: postgres-daily-backup
spec:
    schedule: "0 0 * * *"
    jobTemplate:
        spec:
            template:
                metadata:
                    labels: 
                        parent: cronjobpgback
                spec:
                    containers:
                        name: postgresql-backup
                        image: postgresql-backup
                        command: 
                            - scripts/pg_backup.sh
                        env:
                            - name: BACKUP_USER
                              valueFrom:
                                  secretKeyRef:
                                      name: app_secrets
                                      key: dbUser
                            - name: HOSTNAME
                              valueFrom:
                                  secretKeyRef:
                                      name: app_secrets
                                      key: dbHost
                            - name: CONTEXT_DIR
                              valueFrom:
                                  configMapKeyRef:
                                      name: app_config
                                      key: contextDir
